/**
 * Embedded built-in theme data.
 *
 * Theme JSON is inlined here so the compiled Perry binary has the data
 * baked in — no filesystem reads at runtime.
 */

import type { ThemeData } from './theme-loader';

export const HONE_DARK: ThemeData = {
  name: 'Hone Dark',
  type: 'dark',
  colors: {
    'editor.background': '#1e1e1e',
    'editor.foreground': '#d4d4d4',
    'editor.selectionBackground': '#264f78',
    'editor.lineHighlightBackground': '#2a2d2e',
    'editor.findMatchBackground': '#515c6a',
    'editor.findMatchHighlightBackground': '#ea5c0055',
    'editorCursor.foreground': '#aeafad',
    'editorLineNumber.foreground': '#858585',
    'editorLineNumber.activeForeground': '#c6c6c6',
    'editorGutter.addedBackground': '#587c0c',
    'editorGutter.modifiedBackground': '#0c7d9d',
    'editorGutter.deletedBackground': '#94151b',
    'editorIndentGuide.background': '#404040',
    'editorIndentGuide.activeBackground': '#707070',
    'editorWhitespace.foreground': '#3b3b3b',
    'editorBracketMatch.background': '#0064001a',
    'editorBracketMatch.border': '#888888',
    'activityBar.background': '#333333',
    'activityBar.foreground': '#ffffff',
    'activityBar.inactiveForeground': '#ffffff99',
    'sideBar.background': '#252526',
    'sideBar.foreground': '#cccccc',
    'sideBarTitle.foreground': '#bbbbbb',
    'sideBarSectionHeader.background': '#80808033',
    'titleBar.activeBackground': '#3c3c3c',
    'titleBar.activeForeground': '#cccccc',
    'titleBar.inactiveBackground': '#3c3c3c',
    'tab.activeBackground': '#1e1e1e',
    'tab.activeForeground': '#ffffff',
    'tab.inactiveBackground': '#2d2d2d',
    'tab.inactiveForeground': '#ffffff80',
    'tab.border': '#252526',
    'statusBar.background': '#007acc',
    'statusBar.foreground': '#ffffff',
    'statusBar.debuggingBackground': '#cc6633',
    'panel.background': '#1e1e1e',
    'panel.border': '#80808059',
    'terminal.background': '#1e1e1e',
    'terminal.foreground': '#cccccc',
    'input.background': '#3c3c3c',
    'input.foreground': '#cccccc',
    'input.border': '#3c3c3c',
    'input.placeholderForeground': '#a6a6a6',
    'button.background': '#0e639c',
    'button.foreground': '#ffffff',
    'button.hoverBackground': '#1177bb',
    'list.activeSelectionBackground': '#04395e',
    'list.activeSelectionForeground': '#ffffff',
    'list.hoverBackground': '#2a2d2e',
    'list.focusBackground': '#04395e',
    'badge.background': '#4d4d4d',
    'badge.foreground': '#ffffff',
    'focusBorder': '#007fd4',
    'commandPalette.background': '#252526',
    'commandPalette.foreground': '#cccccc',
  },
  tokenColors: [
    { name: 'Comment', scope: ['comment', 'punctuation.definition.comment'], settings: { foreground: '#6a9955', fontStyle: 'italic' } },
    { name: 'String', scope: ['string', 'string.quoted'], settings: { foreground: '#ce9178' } },
    { name: 'Number', scope: ['constant.numeric'], settings: { foreground: '#b5cea8' } },
    { name: 'Boolean/Null', scope: ['constant.language'], settings: { foreground: '#569cd6' } },
    { name: 'Keyword', scope: ['keyword', 'storage.type', 'storage.modifier'], settings: { foreground: '#569cd6' } },
    { name: 'Control keyword', scope: ['keyword.control'], settings: { foreground: '#c586c0' } },
    { name: 'Operator', scope: ['keyword.operator'], settings: { foreground: '#d4d4d4' } },
    { name: 'Function declaration', scope: ['entity.name.function', 'support.function'], settings: { foreground: '#dcdcaa' } },
    { name: 'Function call', scope: ['meta.function-call'], settings: { foreground: '#dcdcaa' } },
    { name: 'Type', scope: ['entity.name.type', 'support.type', 'support.class'], settings: { foreground: '#4ec9b0' } },
    { name: 'Class', scope: ['entity.name.class', 'entity.other.inherited-class'], settings: { foreground: '#4ec9b0' } },
    { name: 'Interface', scope: ['entity.name.interface'], settings: { foreground: '#4ec9b0', fontStyle: 'italic' } },
    { name: 'Variable', scope: ['variable', 'variable.other'], settings: { foreground: '#9cdcfe' } },
    { name: 'Parameter', scope: ['variable.parameter'], settings: { foreground: '#9cdcfe' } },
    { name: 'Property', scope: ['variable.other.property', 'variable.other.object.property'], settings: { foreground: '#9cdcfe' } },
    { name: 'Constant', scope: ['variable.other.constant'], settings: { foreground: '#4fc1ff' } },
    { name: 'Tag (HTML/JSX)', scope: ['entity.name.tag'], settings: { foreground: '#569cd6' } },
    { name: 'Tag attribute', scope: ['entity.other.attribute-name'], settings: { foreground: '#9cdcfe', fontStyle: 'italic' } },
    { name: 'Punctuation', scope: ['punctuation'], settings: { foreground: '#d4d4d4' } },
    { name: 'Decorator/Annotation', scope: ['meta.decorator', 'meta.annotation'], settings: { foreground: '#dcdcaa' } },
    { name: 'Regex', scope: ['string.regexp'], settings: { foreground: '#d16969' } },
    { name: 'Escape character', scope: ['constant.character.escape'], settings: { foreground: '#d7ba7d' } },
  ],
  semanticHighlighting: true,
  semanticTokenColors: {
    'namespace': '#4ec9b0',
    'type': '#4ec9b0',
    'class': '#4ec9b0',
    'enum': '#4ec9b0',
    'interface': { foreground: '#4ec9b0', fontStyle: 'italic' },
    'struct': '#4ec9b0',
    'typeParameter': '#4ec9b0',
    'parameter': '#9cdcfe',
    'variable': '#9cdcfe',
    'variable.readonly': '#4fc1ff',
    'property': '#9cdcfe',
    'enumMember': '#4fc1ff',
    'function': '#dcdcaa',
    'method': '#dcdcaa',
    'macro': '#569cd6',
    'keyword': '#569cd6',
    'comment': { foreground: '#6a9955', fontStyle: 'italic' },
    'string': '#ce9178',
    'number': '#b5cea8',
    'regexp': '#d16969',
    'operator': '#d4d4d4',
    'decorator': '#dcdcaa',
  },
};

export const HONE_LIGHT: ThemeData = {
  name: 'Hone Light',
  type: 'light',
  colors: {
    'editor.background': '#ffffff',
    'editor.foreground': '#4c4f69',
    'editor.selectionBackground': '#bcc0cc',
    'editor.lineHighlightBackground': '#e6e9ef',
    'editor.findMatchBackground': '#df8e1d40',
    'editor.findMatchHighlightBackground': '#df8e1d20',
    'editorCursor.foreground': '#dc8a78',
    'editorLineNumber.foreground': '#8c8fa1',
    'editorLineNumber.activeForeground': '#4c4f69',
    'editorGutter.addedBackground': '#40a02b',
    'editorGutter.modifiedBackground': '#1e66f5',
    'editorGutter.deletedBackground': '#d20f39',
    'editorIndentGuide.background': '#ccd0da',
    'editorIndentGuide.activeBackground': '#bcc0cc',
    'editorWhitespace.foreground': '#ccd0da',
    'editorBracketMatch.background': '#bcc0cc80',
    'editorBracketMatch.border': '#1e66f5',
    'activityBar.background': '#e6e9ef',
    'activityBar.foreground': '#4c4f69',
    'activityBar.inactiveForeground': '#8c8fa1',
    'sideBar.background': '#e6e9ef',
    'sideBar.foreground': '#4c4f69',
    'sideBarTitle.foreground': '#4c4f69',
    'sideBarSectionHeader.background': '#dce0e8',
    'titleBar.activeBackground': '#e6e9ef',
    'titleBar.activeForeground': '#4c4f69',
    'titleBar.inactiveBackground': '#e6e9ef',
    'tab.activeBackground': '#ffffff',
    'tab.activeForeground': '#4c4f69',
    'tab.inactiveBackground': '#e6e9ef',
    'tab.inactiveForeground': '#8c8fa1',
    'tab.border': '#e6e9ef',
    'statusBar.background': '#e6e9ef',
    'statusBar.foreground': '#4c4f69',
    'statusBar.debuggingBackground': '#fe640b',
    'panel.background': '#e6e9ef',
    'panel.border': '#ccd0da',
    'terminal.background': '#ffffff',
    'terminal.foreground': '#4c4f69',
    'input.background': '#ccd0da',
    'input.foreground': '#4c4f69',
    'input.border': '#bcc0cc',
    'input.placeholderForeground': '#8c8fa1',
    'button.background': '#1e66f5',
    'button.foreground': '#ffffff',
    'button.hoverBackground': '#2a6ef5',
    'list.activeSelectionBackground': '#bcc0cc',
    'list.activeSelectionForeground': '#4c4f69',
    'list.hoverBackground': '#ccd0da',
    'list.focusBackground': '#bcc0cc',
    'badge.background': '#1e66f5',
    'badge.foreground': '#ffffff',
    'focusBorder': '#1e66f5',
    'commandPalette.background': '#ffffff',
    'commandPalette.foreground': '#4c4f69',
  },
  tokenColors: [
    { name: 'Comment', scope: ['comment', 'punctuation.definition.comment'], settings: { foreground: '#8c8fa1', fontStyle: 'italic' } },
    { name: 'String', scope: ['string', 'string.quoted'], settings: { foreground: '#40a02b' } },
    { name: 'Number', scope: ['constant.numeric'], settings: { foreground: '#fe640b' } },
    { name: 'Boolean/Null', scope: ['constant.language'], settings: { foreground: '#fe640b' } },
    { name: 'Keyword', scope: ['keyword', 'storage.type', 'storage.modifier'], settings: { foreground: '#8839ef' } },
    { name: 'Control keyword', scope: ['keyword.control'], settings: { foreground: '#8839ef' } },
    { name: 'Operator', scope: ['keyword.operator'], settings: { foreground: '#179299' } },
    { name: 'Function declaration', scope: ['entity.name.function', 'support.function'], settings: { foreground: '#1e66f5' } },
    { name: 'Function call', scope: ['meta.function-call'], settings: { foreground: '#1e66f5' } },
    { name: 'Type', scope: ['entity.name.type', 'support.type', 'support.class'], settings: { foreground: '#df8e1d' } },
    { name: 'Class', scope: ['entity.name.class', 'entity.other.inherited-class'], settings: { foreground: '#df8e1d' } },
    { name: 'Interface', scope: ['entity.name.interface'], settings: { foreground: '#df8e1d', fontStyle: 'italic' } },
    { name: 'Variable', scope: ['variable', 'variable.other'], settings: { foreground: '#4c4f69' } },
    { name: 'Parameter', scope: ['variable.parameter'], settings: { foreground: '#fe640b' } },
    { name: 'Property', scope: ['variable.other.property', 'variable.other.object.property'], settings: { foreground: '#179299' } },
    { name: 'Constant', scope: ['variable.other.constant'], settings: { foreground: '#fe640b' } },
    { name: 'Tag (HTML/JSX)', scope: ['entity.name.tag'], settings: { foreground: '#d20f39' } },
    { name: 'Tag attribute', scope: ['entity.other.attribute-name'], settings: { foreground: '#df8e1d', fontStyle: 'italic' } },
    { name: 'Punctuation', scope: ['punctuation'], settings: { foreground: '#7c7f93' } },
    { name: 'Decorator/Annotation', scope: ['meta.decorator', 'meta.annotation'], settings: { foreground: '#df8e1d' } },
    { name: 'Regex', scope: ['string.regexp'], settings: { foreground: '#ea76cb' } },
    { name: 'Escape character', scope: ['constant.character.escape'], settings: { foreground: '#ea76cb' } },
  ],
  semanticHighlighting: true,
  semanticTokenColors: {
    'namespace': '#8839ef',
    'type': '#df8e1d',
    'class': '#df8e1d',
    'enum': '#df8e1d',
    'interface': { foreground: '#df8e1d', fontStyle: 'italic' },
    'struct': '#df8e1d',
    'typeParameter': '#df8e1d',
    'parameter': '#fe640b',
    'variable': '#4c4f69',
    'variable.readonly': '#fe640b',
    'property': '#179299',
    'enumMember': '#fe640b',
    'function': '#1e66f5',
    'method': '#1e66f5',
    'macro': '#d20f39',
    'keyword': '#8839ef',
    'comment': { foreground: '#8c8fa1', fontStyle: 'italic' },
    'string': '#40a02b',
    'number': '#fe640b',
    'regexp': '#ea76cb',
    'operator': '#179299',
    'decorator': '#df8e1d',
  },
};
