/**
 * Embedded built-in theme data.
 *
 * Theme JSON is inlined here so the compiled Perry binary has the data
 * baked in — no filesystem reads at runtime.
 */

import type { ThemeData } from './theme-loader';

export const HONE_DARK: ThemeData = {
  name: 'Hone Dark',
  type: 'dark',
  colors: {
    'editor.background': '#1e1e2e',
    'editor.foreground': '#cdd6f4',
    'editor.selectionBackground': '#45475a',
    'editor.lineHighlightBackground': '#2a2b3d',
    'editor.findMatchBackground': '#f9e2af40',
    'editor.findMatchHighlightBackground': '#f9e2af20',
    'editorCursor.foreground': '#f5e0dc',
    'editorLineNumber.foreground': '#6c7086',
    'editorLineNumber.activeForeground': '#cdd6f4',
    'editorGutter.addedBackground': '#a6e3a1',
    'editorGutter.modifiedBackground': '#89b4fa',
    'editorGutter.deletedBackground': '#f38ba8',
    'editorIndentGuide.background': '#313244',
    'editorIndentGuide.activeBackground': '#45475a',
    'editorWhitespace.foreground': '#313244',
    'editorBracketMatch.background': '#45475a80',
    'editorBracketMatch.border': '#89b4fa',
    'activityBar.background': '#181825',
    'activityBar.foreground': '#cdd6f4',
    'activityBar.inactiveForeground': '#6c7086',
    'sideBar.background': '#181825',
    'sideBar.foreground': '#cdd6f4',
    'sideBarTitle.foreground': '#cdd6f4',
    'sideBarSectionHeader.background': '#1e1e2e',
    'titleBar.activeBackground': '#181825',
    'titleBar.activeForeground': '#cdd6f4',
    'titleBar.inactiveBackground': '#181825',
    'tab.activeBackground': '#1e1e2e',
    'tab.activeForeground': '#cdd6f4',
    'tab.inactiveBackground': '#181825',
    'tab.inactiveForeground': '#6c7086',
    'tab.border': '#181825',
    'statusBar.background': '#181825',
    'statusBar.foreground': '#cdd6f4',
    'statusBar.debuggingBackground': '#fab387',
    'panel.background': '#181825',
    'panel.border': '#313244',
    'terminal.background': '#1e1e2e',
    'terminal.foreground': '#cdd6f4',
    'input.background': '#313244',
    'input.foreground': '#cdd6f4',
    'input.border': '#45475a',
    'input.placeholderForeground': '#6c7086',
    'button.background': '#89b4fa',
    'button.foreground': '#1e1e2e',
    'button.hoverBackground': '#74c7ec',
    'list.activeSelectionBackground': '#45475a',
    'list.activeSelectionForeground': '#cdd6f4',
    'list.hoverBackground': '#313244',
    'list.focusBackground': '#45475a',
    'badge.background': '#89b4fa',
    'badge.foreground': '#1e1e2e',
    'focusBorder': '#89b4fa',
    'commandPalette.background': '#1e1e2e',
    'commandPalette.foreground': '#cdd6f4',
  },
  tokenColors: [
    { name: 'Comment', scope: ['comment', 'punctuation.definition.comment'], settings: { foreground: '#6c7086', fontStyle: 'italic' } },
    { name: 'String', scope: ['string', 'string.quoted'], settings: { foreground: '#a6e3a1' } },
    { name: 'Number', scope: ['constant.numeric'], settings: { foreground: '#fab387' } },
    { name: 'Boolean/Null', scope: ['constant.language'], settings: { foreground: '#fab387' } },
    { name: 'Keyword', scope: ['keyword', 'storage.type', 'storage.modifier'], settings: { foreground: '#cba6f7' } },
    { name: 'Control keyword', scope: ['keyword.control'], settings: { foreground: '#cba6f7' } },
    { name: 'Operator', scope: ['keyword.operator'], settings: { foreground: '#89dceb' } },
    { name: 'Function declaration', scope: ['entity.name.function', 'support.function'], settings: { foreground: '#89b4fa' } },
    { name: 'Function call', scope: ['meta.function-call'], settings: { foreground: '#89b4fa' } },
    { name: 'Type', scope: ['entity.name.type', 'support.type', 'support.class'], settings: { foreground: '#f9e2af' } },
    { name: 'Class', scope: ['entity.name.class', 'entity.other.inherited-class'], settings: { foreground: '#f9e2af' } },
    { name: 'Interface', scope: ['entity.name.interface'], settings: { foreground: '#f9e2af', fontStyle: 'italic' } },
    { name: 'Variable', scope: ['variable', 'variable.other'], settings: { foreground: '#cdd6f4' } },
    { name: 'Parameter', scope: ['variable.parameter'], settings: { foreground: '#fab387' } },
    { name: 'Property', scope: ['variable.other.property', 'variable.other.object.property'], settings: { foreground: '#89dceb' } },
    { name: 'Constant', scope: ['variable.other.constant'], settings: { foreground: '#fab387' } },
    { name: 'Tag (HTML/JSX)', scope: ['entity.name.tag'], settings: { foreground: '#f38ba8' } },
    { name: 'Tag attribute', scope: ['entity.other.attribute-name'], settings: { foreground: '#f9e2af', fontStyle: 'italic' } },
    { name: 'Punctuation', scope: ['punctuation'], settings: { foreground: '#9399b2' } },
    { name: 'Decorator/Annotation', scope: ['meta.decorator', 'meta.annotation'], settings: { foreground: '#f9e2af' } },
    { name: 'Regex', scope: ['string.regexp'], settings: { foreground: '#f5c2e7' } },
    { name: 'Escape character', scope: ['constant.character.escape'], settings: { foreground: '#f5c2e7' } },
  ],
  semanticHighlighting: true,
  semanticTokenColors: {
    'namespace': '#cba6f7',
    'type': '#f9e2af',
    'class': '#f9e2af',
    'enum': '#f9e2af',
    'interface': { foreground: '#f9e2af', fontStyle: 'italic' },
    'struct': '#f9e2af',
    'typeParameter': '#f9e2af',
    'parameter': '#fab387',
    'variable': '#cdd6f4',
    'variable.readonly': '#fab387',
    'property': '#89dceb',
    'enumMember': '#fab387',
    'function': '#89b4fa',
    'method': '#89b4fa',
    'macro': '#f38ba8',
    'keyword': '#cba6f7',
    'comment': { foreground: '#6c7086', fontStyle: 'italic' },
    'string': '#a6e3a1',
    'number': '#fab387',
    'regexp': '#f5c2e7',
    'operator': '#89dceb',
    'decorator': '#f9e2af',
  },
};
